<script setup>
import { ref, computed, onMounted } from 'vue'
import { createClient } from '@supabase/supabase-js'
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||'https://dpiwdhtbhwjgatvcfkcb.supabase.co',import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY')
const session=ref(null),profile=ref(null),wallet=ref(null),txs=ref([]),loading=ref(true),busy=ref(false),error=ref(''),notice=ref(''),mode=ref('login'),tab=ref('home'),sendOpen=ref(false),receiveOpen=ref(false),profileOpen=ref(false)
const auth=ref({name:'',email:'',password:''}),send=ref({email:'',amount:'',note:''}),name=ref('')
const balance=computed(()=>Number(wallet.value?wallet.value.balance:0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}))
const first=computed(()=>((profile.value&&profile.value.full_name)||((session.value&&session.value.user.email)||'there').split('@')[0]).split(' ')[0])
const initial=computed(()=>(((profile.value&&profile.value.full_name)||(session.value&&session.value.user.email)||'A')[0]).toUpperCase())
const outgoing=x=>x.sender_id===session.value.user.id
const date=x=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(x))
const clear=()=>{error.value='';notice.value=''}
const msg=x=>String(x||'Something went wrong.').replace('Invalid login credentials','Email or password is incorrect.').replace('User already registered','That email is already registered.').replace('Email not confirmed','Confirm your email first, then sign in.')
async function load(){const id=session.value.user.id;const filter='sender_id.eq.'+id+',recipient_id.eq.'+id;const [p,w,t]=await Promise.all([supabase.from('asal_profiles').select('*').eq('id',id).single(),supabase.from('asal_wallets').select('*').eq('user_id',id).single(),supabase.from('asal_transactions').select('*').or(filter).order('created_at',{ascending:false}).limit(50)]);if(p.error)throw p.error;if(w.error)throw w.error;if(t.error)throw t.error;profile.value=p.data;wallet.value=w.data;txs.value=t.data||[];name.value=p.data.full_name||''}
async function authSubmit(){clear();busy.value=true;try{if(mode.value==='register'){const r=await supabase.auth.signUp({email:auth.value.email.trim(),password:auth.value.password,options:{data:{full_name:auth.value.name.trim()}}});if(r.error)throw r.error;notice.value=r.data.session?'Account ready.':'Account created. Check email confirmation if enabled.'}else{const r=await supabase.auth.signInWithPassword({email:auth.value.email.trim(),password:auth.value.password});if(r.error)throw r.error}}catch(e){error.value=msg(e.message)}finally{busy.value=false}}
async function sendMoney(){clear();const amount=Number(send.value.amount);if(!send.value.email.trim())return error.value='Enter a recipient email.';if(!amount||amount<=0)return error.value='Enter a valid amount.';busy.value=true;try{const r=await supabase.rpc('asal_send_money',{recipient_email:send.value.email.trim(),transfer_amount:amount,transfer_note:send.value.note.trim()||null});if(r.error)throw r.error;sendOpen.value=false;send.value={email:'',amount:'',note:''};notice.value='$'+amount.toFixed(2)+' sent.';await load()}catch(e){error.value=msg(e.message)}finally{busy.value=false}}
async function save(){clear();if(!name.value.trim())return error.value='Enter your name.';const r=await supabase.from('asal_profiles').update({full_name:name.value.trim()}).eq('id',session.value.user.id);if(r.error)return error.value=msg(r.error.message);profile.value.full_name=name.value.trim();profileOpen.value=false;notice.value='Profile updated.'}
async function logout(){await supabase.auth.signOut();session.value=null;profile.value=null;wallet.value=null;txs.value=[]}
onMounted(async()=>{const r=await supabase.auth.getSession();session.value=r.data.session;if(session.value)try{await load()}catch(e){error.value=msg(e.message)};supabase.auth.onAuthStateChange(async(_,s)=>{session.value=s;if(s)try{await load()}catch(e){error.value=msg(e.message)}});loading.value=false})
</script>
<template>
<div class="shell">
<div v-if="loading" class="splash"><b>A</b><strong>Asal Pay</strong><span>Loading…</span></div>
<main v-else-if="!session" class="auth"><div class="brand"><b>A</b><div><small>DIGITAL WALLET</small><h1>Asal Pay</h1></div></div><section class="card"><label class="demo">● DEMO • VIRTUAL FUNDS</label><h2>{{mode==='login'?'Welcome back':'Create your wallet'}}</h2><p>Simple wallet demonstration with Supabase.</p><form @submit.prevent="authSubmit"><label v-if="mode==='register'">Full name<input v-model="auth.name" required placeholder="Your name"></label><label>Email<input v-model="auth.email" required type="email" placeholder="you@example.com"></label><label>Password<input v-model="auth.password" required minlength="6" type="password" placeholder="At least 6 characters"></label><button class="primary" :disabled="busy">{{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}}</button></form><div v-if="error" class="alert bad">{{error}}</div><div v-if="notice" class="alert good">{{notice}}</div><button class="link" @click="mode=mode==='login'?'register':'login';clear()">{{mode==='login'?'New here? Create an account':'Already registered? Sign in'}}</button></section><small class="foot">No real money is moved in this demo.</small></main>
<main v-else class="phone"><header><div><small>ASAL PAY</small><h1>Hello, {{first}}</h1></div><button class="avatar" @click="profileOpen=true">{{initial}}</button></header><div v-if="error" class="alert bad global">{{error}} <button @click="error=''">×</button></div><div v-if="notice" class="alert good global">{{notice}} <button @click="notice=''">×</button></div>
<section v-if="tab==='home'" class="content"><div class="wallet"><div><span>Available balance</span><em>DEMO</em></div><strong>$ {{balance}}</strong><footer>USD • Virtual wallet</footer></div><div class="actions"><button @click="clear();sendOpen=true"><i>↗</i><b>Send</b><small>Transfer money</small></button><button @click="clear();receiveOpen=true"><i>↓</i><b>Receive</b><small>Share details</small></button></div><div class="head"><h2>Recent activity</h2><button @click="tab='activity'">See all</button></div><div v-if="txs.length" class="list"><article v-for="x in txs.slice(0,5)" :key="x.id"><i :class="outgoing(x)?'red':'green'">{{outgoing(x)?'↗':'↙'}}</i><div><b>{{outgoing(x)?'Money sent':'Money received'}}</b><span>{{x.note||'Transfer'}}</span><small>{{date(x.created_at)}}</small></div><strong :class="outgoing(x)?'redtext':'greentext'">{{outgoing(x)?'-':'+'}}${{Number(x.amount).toFixed(2)}}</strong></article></div><div v-else class="empty"><b>No transactions yet</b><span>Send money to another demo account to see activity.</span></div><div class="note"><b>Demo environment</b><span>New accounts start with $1,000 virtual funds. Real payment rails are not connected.</span></div></section>
<section v-else-if="tab==='activity'" class="content"><div class="title"><small>WALLET</small><h2>Activity</h2><p>Your latest virtual-money movements.</p></div><div class="list"><article v-for="x in txs" :key="x.id"><i :class="outgoing(x)?'red':'green'">{{outgoing(x)?'↗':'↙'}}</i><div><b>{{outgoing(x)?'Money sent':'Money received'}}</b><span>{{x.note||'Transfer'}}</span><small>{{date(x.created_at)}}</small></div><strong :class="outgoing(x)?'redtext':'greentext'">{{outgoing(x)?'-':'+'}}${{Number(x.amount).toFixed(2)}}</strong></article></div></section>
<section v-else class="content"><div class="title"><small>ACCOUNT</small><h2>Profile</h2><p>{{session.user.email}}</p></div><div class="profile"><div class="avatar">{{initial}}</div><div><b>{{profile && profile.full_name || 'Asal Pay user'}}</b><span>{{session.user.email}}</span></div></div><button class="wide" @click="profileOpen=true">Edit profile</button><button class="wide danger" @click="logout">Sign out</button></section>
<nav><button :class="{active:tab==='home'}" @click="tab='home'">⌂<small>Home</small></button><button :class="{active:tab==='activity'}" @click="tab='activity'">≡<small>Activity</small></button><button :class="{active:tab==='profile'}" @click="tab='profile'">○<small>Profile</small></button></nav></main>
<div v-if="sendOpen" class="backdrop" @click.self="sendOpen=false"><section class="modal"><button class="close" @click="sendOpen=false">×</button><small>TRANSFER</small><h2>Send money</h2><p>Virtual transfer, instant in the demo.</p><form @submit.prevent="sendMoney"><label>Recipient email<input v-model="send.email" required type="email" placeholder="friend@example.com"></label><label>Amount<input v-model="send.amount" required type="number" min=".01" step=".01" placeholder="50.00"></label><label>Note <small>Optional</small><input v-model="send.note" placeholder="Lunch, transport…"></label><button class="primary" :disabled="busy">{{busy?'Sending…':'Send money'}}</button></form></section></div>
<div v-if="receiveOpen" class="backdrop" @click.self="receiveOpen=false"><section class="modal receive"><button class="close" @click="receiveOpen=false">×</button><small>RECEIVE</small><h2>Your details</h2><div class="receivebox"><b>A</b><strong>{{profile && profile.full_name || 'Asal Pay user'}}</strong><span>{{session.user.email}}</span><small>Share this email with another demo user.</small></div><button class="primary" @click="receiveOpen=false">Done</button></section></div>
<div v-if="profileOpen" class="backdrop" @click.self="profileOpen=false"><section class="modal"><button class="close" @click="profileOpen=false">×</button><small>ACCOUNT</small><h2>Edit profile</h2><form @submit.prevent="save"><label>Full name<input v-model="name" required></label><label>Email<input :value="session.user.email" disabled></label><button class="primary">Save changes</button></form></section></div>
</div></template>